# Generated by Django 4.1.5 on 2023-02-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complate',
            new_name='complete',
        ),
    ]
